# Generated by Django 6.0.3 on 2026-03-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_alter_notification_pet_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrequest',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='petrequest',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
